language: node_js
node_js:
  - "6"
sudo: false
before_install:
  - npm install -g http-server
install:
  - npm install
services:
  - http-server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - http-server
  - sleep 3
branches:
 only: master
